version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:18545/
      ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:18545/
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:18546/
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'false'
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'false'
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      CHAIN_ID: '813'
      EXCHANGE_RATES_MARKET_CAP_SOURCE: 'coin_market_cap'
      EXCHANGE_RATES_PRICE_SOURCE: 'coin_market_cap'
      EXCHANGE_RATES_COINMARKETCAP_API_KEY: 'b082eb60-9ca2-43a8-817e-5df872cbba64'
      EXCHANGE_RATES_COINMARKETCAP_COIN_ID: '15658'
      MICROSERVICE_VISUALIZE_SOL2UML_URL: 'http://host.docker.internal:8152/'
      MICROSERVICE_SIG_PROVIDER_URL: 'http://host.docker.internal:8151/'
      API_RATE_LIMIT: 1000
    ports:
      - 4000:4000

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
